data_param:
    dataset_type: 'EEGDenoiseNet'
    noise_type: 'EOG'
    data_shape: [1, 512]
    num_workers: 1
    ratio_of_dataset: '8:1:1'
    save_metric: False
    save_eval_result: False 
    save_ablation_result: False 
    save_qualitative_result: True 


model_name: 'proposed_nonalternation'
model_param:
    use_tensorboard: False
    proposed: 
        encoder:
            kernel_size: 10 #30
            encoder_dim: 256
        separator:
            K: 20 #20
            stack_num: 3
            layer_num_local: 6
            layer_num_global: 3
            norm: 'ln'
            feature_dim: 256 
            hidden_dim: 256
            kernel_size: 3
            dropout_rate: 0.2
        decoder:
            None
    tasnet:
        channel: 1
        encoder_dim: 256 
        feature_dim: 256
        sample_rate: None
        win: 30
        layer_num: 5 
        stack_num: 7
        kernel_size: 3
        num_speaker: 2
        causal: False
        dropout_rate: 0.2
    proposed_dilated_1:
        encoder:
            kernel_size: 10 #30
            encoder_dim: 256
        separator:
            K: 20
            stack_num: 3
            layer_num_local: 6
            layer_num_global: 3
            norm: 'ln'
            feature_dim: 256 
            hidden_dim: 256
            kernel_size: 3
            dropout_rate: 0.2
        decoder:
            None
    proposed_all_local:
        encoder:
            kernel_size: 10 #30
            encoder_dim: 256
        separator:
            K: 20 #20
            stack_num: 3
            layer_num_local: 6
            layer_num_global: 3
            norm: 'ln'
            feature_dim: 256 
            hidden_dim: 256
            kernel_size: 3
            dropout_rate: 0.2
        decoder:
            None
    proposed_all_global:
        encoder:
            kernel_size: 10 #30
            encoder_dim: 256
        separator:
            K: 20
            stack_num: 3
            layer_num_local: 6
            layer_num_global: 3
            norm: 'ln'
            feature_dim: 256 
            hidden_dim: 256
            kernel_size: 3
            dropout_rate: 0.2
        decoder:
            None
    proposed_nonalternation:
        encoder:
            kernel_size: 10 #30
            encoder_dim: 256
        separator:
            K: 20
            stack_num: 3
            layer_num_local: 6
            layer_num_global: 3
            norm: 'ln'
            feature_dim: 256 
            hidden_dim: 256
            kernel_size: 3
            dropout_rate: 0.2
        decoder:
            None    
    proposed_nonalternation_global_first:
        encoder:
            kernel_size: 10 #30
            encoder_dim: 256
        separator:
            K: 20
            stack_num: 3
            layer_num_local: 6
            layer_num_global: 3
            norm: 'ln'
            feature_dim: 256 
            hidden_dim: 256
            kernel_size: 3
            dropout_rate: 0.2
        decoder:
            None
    raw: 
        encoder:
            kernel_size: 30
            encoder_dim: 256
        separator:
            K: 20
            stack_num: 3
            layer_num_local: 6
            layer_num_global: 3
            norm: 'ln'
            feature_dim: 256 
            hidden_dim: 256
            kernel_size: 3
            dropout_rate: 0.2
        decoder:
            None
    without_global: 
        encoder:
            kernel_size: 30
            encoder_dim: 256
        separator:
            K: 20
            stack_num: 3
            layer_num_local: 6
            layer_num_global: 3
            norm: 'ln'
            feature_dim: 256 
            hidden_dim: 256
            kernel_size: 3
            dropout_rate: 0.2
        decoder:
            None

training:
    n_epochs: 20000
    validation_freq_in_epoch: 1
    patience: 20
    batch_size: 128
    valid_size: 128
    eval_size: 128

evaluation:
    model_path: /z3/home/xai_test/wch/paper_related/03-EEG_DENOISE/checkpoints/(cfg-2024-07-09-EEGDenoiseNet-EOG)-(EOG)-(proposed_nonalternation)/checkpoint-EOG-(2024-07-17-11-12-37).pth

optim_param:
    weight_decay: 0.000
    optimizer: "Adam"
    loss: 
        name: 'mse, lncosh'
        mse:
            weight: 10
        lncosh:
            lamda: 0.1
            weight: 100
    lr: 0.0003
    amsgrad: False
    eps: 0.00000001

device: 'cuda'
gpu_ids: '0'
mode: 'eval'

