data_param:
    dataset_type: 'EEGDenoiseNet'
    noise_type: 'EMG_EOG'
    data_shape: [1, 512]
    num_workers: 1
    ratio_of_dataset: '8:1:1'
    save_metric: False
    save_eval_result: False 
    save_ablation_result: False 
    save_qualitative_result: True 

model_name: 'proposed'
model_param:
    use_tensorboard: False
    proposed: 
        encoder:
            kernel_size: 30  
            encoder_dim: 256
        separator:
            K: 20
            stack_num: 4
            layer_num_local: 6
            layer_num_global: 3
            norm: 'ln'
            feature_dim: 256 
            hidden_dim: 256
            kernel_size: 3
            dropout_rate: 0.2
        decoder:
            None

training:
    n_epochs: 20000
    validation_freq_in_epoch: 1
    patience: 20
    batch_size: 128
    valid_size: 128
    eval_size: 128

evaluation:
    model_path: /z3/home/xai_test/wch/paper_related/03-EEG_DENOISE/checkpoints/(cfg-2024-07-09-EEGDenoiseNet-EMG_EOG)-(EMG_EOG)-(proposed)/checkpoint-EMG_EOG-(2024-07-26-17-22-25).pth


optim_param:
    weight_decay: 0.000
    optimizer: "Adam"
    loss: 
        name: 'mse' #'mse, lncosh'
        mse:
            weight: 1 #10
        lncosh:
            lamda: 0.1
            weight: 100
    lr: 0.0003
    amsgrad: False
    eps: 0.00000001

device: 'cuda'
gpu_ids: '0'
mode: 'eval'

